project:
  type: website
  output-dir: docs
  render:
    - index.qmd

website:
  title: "Microeukaryote deep-sea database"
  navbar:
    left:
      - href: index.qmd
        text: Main

format:
  html:
    theme: slate
    css: slate.scss
    toc: true
    toc-location: left
    number-sections: true
    number-depth: 3



