project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - how-to.qmd
    - db-main.qmd
    - db-taxa.qmd

website:
  title: "Database Darkly"
  navbar:
    left:
      - href: index.qmd
        text: Main
      - href: how-to.qmd
        text: How to use
      - href: db-main.qmd
        text: Database curation
      - href: db-taxa.qmd
        text: Summary of database

format:
  html:
    theme: flatly
    css: solar.scss
    toc: true
    toc-location: left
    number-sections: true
    number-depth: 3



